services:
  web:
    build: .
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=development
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tpcal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      # THIS IS THE FIX: Mount the entire sql directory.
      # Docker will run both .sql files in alphabetical order.
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  live-reload:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    command: >
      sh -c "npm install && node live-reload-server.js"

volumes:
  db_data: