INSERT INTO policies (title, description, category, policy_rank, url) VALUES
  ('Streamline CEQA for Infill Housing','Targeted CEQA streamlining to accelerate infill and transit-oriented housing projects.','Housing & Homelessness',0,'https://www.ppic.org/topics/trending-housing/'),
  ('By-Right Multifamily Near Transit','Allow by-right mid-density housing within 0.5 miles of major transit.','Housing & Homelessness',0,'https://www.ppic.org/topics/trending-housing/'),
  ('Adaptive Reuse of Commercial to Housing','Convert vacant offices/retail to housing with grants and code updates.','Housing & Homelessness',0,'https://www.ppic.org/topics/trending-housing/'),
  ('Statewide Inclusionary Zoning Baseline','Set a floor for inclusionary units with local flexibility.','Housing & Homelessness',0,'https://www.ppic.org/topics/trending-housing/'),
  ('Right to Shelter with Services','Guarantee shelter coupled with treatment and case management.','Housing & Homelessness',0,'https://www.ppic.org/topics/trending-housing/'),
  ('Permanent Supportive Housing Expansion','Scale PSH units with dedicated operating subsidies.','Housing & Homelessness',0,'https://www.ppic.org/topics/trending-housing/'),
  ('Encampment Resolution Standards','State standards for humane, outcomes-focused encampment resolution.','Housing & Homelessness',0,'https://www.ppic.org/topics/trending-housing/'),
  ('Rental Assistance Rapid Re-Housing','Short-term aid to prevent evictions and homelessness returns.','Housing & Homelessness',0,'https://www.ppic.org/topics/trending-housing/'),
  ('Accessory Dwelling Unit Fast-Track','24‑hour ministerial approvals for compliant ADUs.','Housing & Homelessness',0,'https://www.ppic.org/topics/trending-housing/'),
  ('Local Accountability & Housing Elements','Stronger penalties for noncompliant housing elements.','Housing & Homelessness',0,'https://www.ppic.org/topics/trending-housing/'),
  ('Extend Cap-and-Invest to 2045 Implementation','Operationalize extended cap-and-invest with equity guardrails.','Climate & Energy',0,'https://ww2.arb.ca.gov/our-work/programs/cap-and-trade-program'),
  ('Regional Power Market Integration','Join a West-wide market to lower costs and improve reliability.','Climate & Energy',0,'https://ww2.arb.ca.gov/our-work/programs/cap-and-trade-program'),
  ('Utility Wildfire Risk Mitigation Financing','Stabilize utilities with safety and oversight conditions.','Climate & Energy',0,'https://ww2.arb.ca.gov/our-work/programs/cap-and-trade-program'),
  ('Distributed Solar + Storage for Low‑Income','Incentives for resilient clean energy in disadvantaged areas.','Climate & Energy',0,'https://ww2.arb.ca.gov/our-work/programs/cap-and-trade-program'),
  ('Offshore Wind Port & Grid Buildout','Fund port upgrades and transmission for offshore wind.','Climate & Energy',0,'https://ww2.arb.ca.gov/our-work/programs/cap-and-trade-program'),
  ('Heavy-Duty Zero-Emission Trucks','Scale ZEV trucks with charging corridors and vouchers.','Climate & Energy',0,'https://ww2.arb.ca.gov/our-work/programs/cap-and-trade-program'),
  ('Oil Well Cleanup & Brownfield Reuse','Orphan well plugging and site reuse programs.','Climate & Energy',0,'https://ww2.arb.ca.gov/our-work/programs/cap-and-trade-program'),
  ('Community Air Monitoring & Enforcement','Expand AB 617 style monitoring and enforcement.','Climate & Energy',0,'https://ww2.arb.ca.gov/our-work/programs/cap-and-trade-program'),
  ('Heat Resilience & Cool Roofs','Standards and funding for urban heat mitigation.','Climate & Energy',0,'https://ww2.arb.ca.gov/our-work/programs/cap-and-trade-program'),
  ('Building Decarbonization Rebates','Point-of-sale electrification rebates for homes.','Climate & Energy',0,'https://ww2.arb.ca.gov/our-work/programs/cap-and-trade-program'),
  ('Drought-Resilient Urban Conservation','Permanent standards for per‑capita urban water use.','Water',0,'https://www.ppic.org/water/'),
  ('SGMA Groundwater Sustainability Acceleration','Support GSA compliance and recharge projects.','Water',0,'https://www.ppic.org/water/'),
  ('Water Recycling & Desal Grants','Scale potable reuse; evaluate brackish desal.','Water',0,'https://www.ppic.org/water/'),
  ('Delta Conveyance & Ecosystem','Balanced conveyance with habitat restoration.','Water',0,'https://www.ppic.org/water/'),
  ('Ag Water Efficiency Modernization','Metering, tech adoption, and incentives.','Water',0,'https://www.ppic.org/water/'),
  ('Small System Drinking Water Upgrades','Fix failing rural systems with technical assistance.','Water',0,'https://www.ppic.org/water/'),
  ('Stormwater Capture & Green Infrastructure','Fund local capture and infiltration projects.','Water',0,'https://www.ppic.org/water/'),
  ('Tribal Water Rights Support','Technical and legal assistance for tribal rights.','Water',0,'https://www.ppic.org/water/'),
  ('Dam Safety & Reservoir Re-ops','Seismic retrofits and smart reoperation.','Water',0,'https://www.ppic.org/water/'),
  ('Watershed Data & Forecast-Informed Ops','Expand FIRO and open data sharing.','Water',0,'https://www.ppic.org/water/'),
  ('Wildfire Home Hardening Grants','Retrofit homes in WUI with fire-resistant materials.','Wildfire',0,'https://www.ppic.org/topics/trending-wildfires/'),
  ('Vegetation Management & Prescribed Fire','Scale fuels treatments with workforce development.','Wildfire',0,'https://www.ppic.org/topics/trending-wildfires/'),
  ('Utility Undergrounding Prioritization','Targeted undergrounding in highest risk corridors.','Wildfire',0,'https://www.ppic.org/topics/trending-wildfires/'),
  ('Insurance Market Stability for WUI','Risk-based pricing with consumer protections.','Wildfire',0,'https://www.ppic.org/topics/trending-wildfires/'),
  ('Community Evacuation Planning','Modernize evacuation maps and alerting.','Wildfire',0,'https://www.ppic.org/topics/trending-wildfires/'),
  ('Post-Fire Watershed Recovery','Rapid stabilization to prevent debris flows.','Wildfire',0,'https://www.ppic.org/topics/trending-wildfires/'),
  ('Firefighter Recruitment & Retention','Career ladders and mental health support.','Wildfire',0,'https://www.ppic.org/topics/trending-wildfires/'),
  ('Air Quality Smoke Response','Clean air centers and HEPA filtration programs.','Wildfire',0,'https://www.ppic.org/topics/trending-wildfires/'),
  ('Hardening Critical Infrastructure','Wildfire resilience for hospitals and water systems.','Wildfire',0,'https://www.ppic.org/topics/trending-wildfires/'),
  ('Insurance Incentives for Mitigation','Premium discounts tied to verified mitigation.','Wildfire',0,'https://www.ppic.org/topics/trending-wildfires/'),
  ('Statewide Safe Streets & Vision Zero','Targeted investments to cut serious injuries.','Transportation',0,'https://www.ppic.org/publication/californians-and-transportation/'),
  ('High-Speed Rail Funding Governance','Transparent milestones and corridor phasing.','Transportation',0,'https://www.ppic.org/publication/californians-and-transportation/'),
  ('EV Charging Backbone Buildout','Fast chargers every 50 miles on corridors.','Transportation',0,'https://www.ppic.org/publication/californians-and-transportation/'),
  ('Transit Operations Stabilization','Prevent service cuts; integrate fares regionally.','Transportation',0,'https://www.ppic.org/publication/californians-and-transportation/'),
  ('Active Transportation Networks','Protected bike lanes and safe routes to school.','Transportation',0,'https://www.ppic.org/publication/californians-and-transportation/'),
  ('Freight Rail & Port Decarbonization','Shore power and zero‑emission cargo handling.','Transportation',0,'https://www.ppic.org/publication/californians-and-transportation/'),
  ('Road Usage Charge Pilots','Long‑term replacement for gas tax.','Transportation',0,'https://www.ppic.org/publication/californians-and-transportation/'),
  ('Complete Streets on State Highways','Caltrans design flexibility for safety.','Transportation',0,'https://www.ppic.org/publication/californians-and-transportation/'),
  ('Transit-Oriented Development Grants','Cap-and-invest to co‑fund TOD infrastructure.','Transportation',0,'https://www.ppic.org/publication/californians-and-transportation/'),
  ('Rural Mobility & Microtransit','On‑demand service for rural and tribal areas.','Transportation',0,'https://www.ppic.org/publication/californians-and-transportation/'),
  ('Pretrial Reform & Court Backlogs','Reduce backlogs; risk-based pretrial practices.','Public Safety & Justice',0,'https://www.ppic.org/topics/criminal-justice/'),
  ('Organized Retail Theft Response','Regional task forces and diversion programs.','Public Safety & Justice',0,'https://www.ppic.org/topics/criminal-justice/'),
  ('Community Violence Intervention','Evidence-based CVI grants in high-need areas.','Public Safety & Justice',0,'https://www.ppic.org/topics/criminal-justice/'),
  ('Corrections Reentry & Job Training','Reduce recidivism with apprenticeships.','Public Safety & Justice',0,'https://www.ppic.org/topics/criminal-justice/'),
  ('Fentanyl Overdose Prevention','Naloxone, testing strips, and treatment access.','Public Safety & Justice',0,'https://www.ppic.org/topics/criminal-justice/'),
  ('Police Accountability & Training','De-escalation, data transparency standards.','Public Safety & Justice',0,'https://www.ppic.org/topics/criminal-justice/'),
  ('Catalytic Converter Theft Controls','Marking, resale limits, and enforcement.','Public Safety & Justice',0,'https://www.ppic.org/topics/criminal-justice/'),
  ('Victim Services Expansion','Trauma-informed services statewide.','Public Safety & Justice',0,'https://www.ppic.org/topics/criminal-justice/'),
  ('Gun Violence Restraining Orders','Awareness and enforcement capacity.','Public Safety & Justice',0,'https://www.ppic.org/topics/criminal-justice/'),
  ('Court Technology Modernization','E-filing and digital access improvements.','Public Safety & Justice',0,'https://www.ppic.org/topics/criminal-justice/'),
  ('Early Literacy & Tutor Corps','High-dosage tutoring for K–3 literacy.','K–12 Education',0,'https://www.ppic.org/topics/k-12-education/'),
  ('Teacher Housing & Pipelines','Affordable housing and residencies for teachers.','K–12 Education',0,'https://www.ppic.org/topics/k-12-education/'),
  ('CTE & STEM Pathways','Modernize labs and industry partnerships.','K–12 Education',0,'https://www.ppic.org/topics/k-12-education/'),
  ('School Facility Modernization','Seismic, HVAC, and air filtration upgrades.','K–12 Education',0,'https://www.ppic.org/topics/k-12-education/'),
  ('Student Mental Health Services','On‑campus counselors and telehealth.','K–12 Education',0,'https://www.ppic.org/topics/k-12-education/'),
  ('Community Schools Expansion','Wraparound services via school hubs.','K–12 Education',0,'https://www.ppic.org/topics/k-12-education/'),
  ('Computer Science for All','State standards and teacher training.','K–12 Education',0,'https://www.ppic.org/topics/k-12-education/'),
  ('Special Education Funding Reform','Simplify formulas; ensure inclusion supports.','K–12 Education',0,'https://www.ppic.org/topics/k-12-education/'),
  ('Chronic Absenteeism Reduction','Data-driven interventions and transit passes.','K–12 Education',0,'https://www.ppic.org/topics/k-12-education/'),
  ('School Nutrition & Farm-to-School','Universal meals and local procurement.','K–12 Education',0,'https://www.ppic.org/topics/k-12-education/'),
  ('UC/CSU Capacity & Completion','Add seats; boost 4‑year graduation rates.','Higher Education',0,'https://www.ppic.org/higher-education/'),
  ('Tuition Stability & Aid Reform','Predictable tuition; expand Cal Grants.','Higher Education',0,'https://www.ppic.org/higher-education/'),
  ('Community College Transfer Pathways','Simplify ADT pathways and advising.','Higher Education',0,'https://www.ppic.org/higher-education/'),
  ('Work-Based Learning & Apprenticeships','Scale earn-and-learn programs.','Higher Education',0,'https://www.ppic.org/higher-education/'),
  ('Basic Needs Centers','Housing, food, and mental health supports.','Higher Education',0,'https://www.ppic.org/higher-education/'),
  ('Online & Hybrid Program Quality','Quality standards for digital instruction.','Higher Education',0,'https://www.ppic.org/higher-education/'),
  ('Research & Innovation Grants','Support climate/health/AI research.','Higher Education',0,'https://www.ppic.org/higher-education/'),
  ('Teacher Credential Modernization','Streamline credentialing and testing.','Higher Education',0,'https://www.ppic.org/higher-education/'),
  ('Student Data Privacy','Stronger protections for ed‑tech.','Higher Education',0,'https://www.ppic.org/higher-education/'),
  ('Debt Relief & Default Prevention','Targeted relief and counseling.','Higher Education',0,'https://www.ppic.org/higher-education/'),
  ('Medi‑Cal Behavioral Health Modernization','Integration and payment reform for BH.','Health & Mental Health',0,'https://www.ppic.org/topics/health-safety-net/'),
  ('FQHC & Rural Clinic Support','Stabilize safety‑net providers.','Health & Mental Health',0,'https://www.ppic.org/topics/health-safety-net/'),
  ('Telehealth Permanency','Make key flexibilities permanent.','Health & Mental Health',0,'https://www.ppic.org/topics/health-safety-net/'),
  ('Workforce: Nurses & Therapists','Scholarships and loan repayment.','Health & Mental Health',0,'https://www.ppic.org/topics/health-safety-net/'),
  ('Public Health Infrastructure','Data systems and lab capacity.','Health & Mental Health',0,'https://www.ppic.org/topics/health-safety-net/'),
  ('Homelessness—Care Coordination','Cross‑agency care management.','Health & Mental Health',0,'https://www.ppic.org/topics/health-safety-net/'),
  ('Reproductive Health Access','Protect and expand access statewide.','Health & Mental Health',0,'https://www.ppic.org/topics/health-safety-net/'),
  ('Opioid Settlement Implementation','Evidence‑based use of settlement funds.','Health & Mental Health',0,'https://www.ppic.org/topics/health-safety-net/'),
  ('Dental Care for Low‑Income Adults','Expand benefits and provider networks.','Health & Mental Health',0,'https://www.ppic.org/topics/health-safety-net/'),
  ('Aging & LTC Behavioral Supports','Integrate BH into LTC settings.','Health & Mental Health',0,'https://www.ppic.org/topics/health-safety-net/'),
  ('Small Business Permitting One‑Stop','Digital portal to reduce startup friction.','Economy & Jobs',0,'https://www.ppic.org/economy/'),
  ('Manufacturing Incentives for Clean Tech','Attract/retain clean manufacturing.','Economy & Jobs',0,'https://www.ppic.org/economy/'),
  ('Tourism Recovery & Cultural Grants','Support local venues and marketing.','Economy & Jobs',0,'https://www.ppic.org/economy/'),
  ('Regional Economic Development Hubs','Cluster strategies outside coastal metros.','Economy & Jobs',0,'https://www.ppic.org/economy/'),
  ('AI & Semiconductor Workforce','Training for high‑demand technical roles.','Economy & Jobs',0,'https://www.ppic.org/economy/'),
  ('Poverty Reduction & EITC Expansion','Expand CalEITC and Young Child Tax Credit.','Economy & Jobs',0,'https://www.ppic.org/economy/'),
  ('Gig Worker Benefits Portability','Pilots for portable benefits.','Economy & Jobs',0,'https://www.ppic.org/economy/'),
  ('State Procurement for Startups','Set‑aside and sandbox for GovTech.','Economy & Jobs',0,'https://www.ppic.org/economy/'),
  ('Rural Broadband Last Mile','Fund last‑mile fiber and wireless.','Economy & Jobs',0,'https://www.ppic.org/economy/'),
  ('Permitting Reform for Major Projects','Time‑certain approvals with accountability.','Economy & Jobs',0,'https://www.ppic.org/economy/');